name: Sync Upstream

on:
  schedule:
    - cron:  '23 23 * * *'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: TG908/fork-sync@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: smicallef
          base: master
          head: master

