name: Sync Upstream

on:
  schedule:
    - cron:  '23 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: sync fork
      run: |
        git remote add upstream https://github.com/smicallef/spiderfoot.git
        git fetch upstream
        git merge -Xtheirs origin/upstream
        git push origin master

